---
- hosts: vagrant
  become: yes
  tasks:
    - name: Installer les paquets génériques sur toutes les machines
      apt:
        name: "{{ item }}"
        state: present
        with_items:
          - vim
          - bash-completion
          - firewalld
    
    - name: Modification du fichier hosts sur toutes les machines
      lineinfile:
        path: /etc/hosts
        line: '{{ item.ip }} {{ item.hostname }}'
        state: present
      with_item:
        - { ip: '192.168.246.10', hostname: 'psmm' }
        - { ip: '192.168.246.11', hostname: 'web' }
        - { ip: '192.168.246.12', hostname: 'ftp' }
        - { ip: '192.168.246.13', hostname: 'db' }

    - name: Démarrer et activer firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Ouverture des ports pour web
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - http
        - https
        - ssh
      when: inventory_hostname == 'web' 

    - name: Ouverture des ports pour ftp
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - ftp
        - ssh
      when: inventory_hostname == 'ftp'

    - name: Ouverture des ports pour db
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - ssh
      when: inventory_hostname == 'db' 

    - name: Crée l'utilisateur Monitor sur tous les postes
      user:
        name: monitor
        password: "{{ 'monitor' | password_hash('sha512') }}"
        comment: Monitor
        shell: /bin/bash
        groups: sudo
        create_home: yes
        state: present

    - name: Génère une paire de clés SSH ED25519 sur le poste psmm
      user:
          name: monitor
          generate_ssh_key: yes
          ssh_key_type: ed25519
          ssh_key_comment: "monitor@{{ $HOSTNAME  }}"
          ssh_key_file: .ssh/monitor
      when: inventory_hostname == 'psmm'

    - name: Copier la clé publique SSH dans le fichier authorized_keys
      authorized_key:
        user: monitor
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      delegate_to: psmm
      with_items:
        - web
        - ftp
        - db
